controllers:
    resource: ../src/Controller/
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: fr|en
home:
    path: /
    controller: App\Controller\HomepageController::index
    defaults:
        _locale: fr|en
